default_language_version:
  # default language version for each language
  python: python3.9

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    # Python
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
    -   id: check-ast # simply checks whether the files parse as valid python.
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8 #command-line utility for enforcing style consistency across Python projects
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        args: [--line-length=79]
