# Generated by Django 4.0 on 2022-01-13 00:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.TextField(verbose_name="Estado")),
                ("city", models.TextField(verbose_name="Ciudad")),
                ("street", models.TextField(verbose_name="Calle")),
                (
                    "zipcode",
                    models.TextField(blank=True, verbose_name="Codigo Zip"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Cantidad",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("SENDED", "Enviado"),
                            ("CREATED", "Creado"),
                            ("RECIEVED", "Recibido"),
                        ],
                        default="CREATED",
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "initial_address",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_initial_address",
                        to="shipment.address",
                    ),
                ),
                ("products", models.ManyToManyField(to="shipment.Product")),
                (
                    "target_address",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_target_address",
                        to="shipment.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShipmentStatusDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.TextField(verbose_name="Estatus")),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="shipment.shipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
