# Generated by Django 4.0 on 2022-01-14 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[("PAID", "Pagado"), ("UNPAID", "No pagado")],
                        default="UNPAID",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "ammount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ]
                    ),
                ),
                (
                    "commerce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                        verbose_name="Cliente comercio",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="invoice.invoice",
                        verbose_name="Envio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceStatusDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "status",
                    models.TextField(
                        choices=[("PAID", "Pagado"), ("UNPAID", "No pagado")],
                        default="UNPAID",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="invoice.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
