# Generated by Django 4.0 on 2022-02-02 21:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipment", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "state",
                    models.TextField(
                        choices=[("PAID", "Pagado"), ("UNPAID", "No pagado")],
                        default="UNPAID",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ammount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ]
                    ),
                ),
                (
                    "commerce",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "comercio"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.user",
                        verbose_name="Cliente comercio",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="shipment.shipment",
                        verbose_name="Envio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceStatusDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("PAID", "Pagado"), ("UNPAID", "No pagado")],
                        default="UNPAID",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="invoice.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
